#!/usr/bin/env bash

count=0
connected="說"
disconnected="ﲁ"

ID="$(ip link | awk '/state UP/ {print $2}')"

while true; do
    if (ping -c 1 archlinux.org || ping -c 1 google.com || ping -c 1 bitbucket.org || ping -c 1 github.com || ping -c 1 sourceforge.net) &>/dev/null; then
        NET_NAME="$(nmcli device status | sed -n 's/^.* connected[ \t]*\([-0-9a-zA-Z]\+\)[ \t]*$/\1/p')"
        if [[ $ID == e* ]]; then
            echo "$connected ${NET_NAME}" ; sleep 25
        else
            echo "$connected ${NET_NAME}" ; sleep 25
        fi
    else
        echo "$disconnected Offline" ; sleep 5
    fi
done
